from datetime import datetime, timezone
import uuid
from sqlalchemy import Column, String, Float, Integer, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import relationship
from backend.db.postgres import Base

def get_utc_now():
    return datetime.now(timezone.utc)

class Job(Base):
    """
    Tracks the lifecycle and configuration of individual Requirement-to-Story pipeline executions.
    """
    __tablename__ = "jobs"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    status = Column(String(50), nullable=False, default="PENDING")  # PENDING, RUNNING, HUMAN_REVIEW, COMPLETED, FAILED
    source_type = Column(String(100), nullable=False)  # FILE, JIRA, CONFLUENCE, SHAREPOINT, GDRIVE
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
    error_message = Column(Text, nullable=True)
    config = Column(JSON, nullable=True)  # custom runtime parameters
    meta_info = Column(JSON, nullable=True)  # document metadata, author, structure

    # Relationships
    requirements = relationship("Requirement", back_populates="job", cascade="all, delete-orphan")
    stories = relationship("Story", back_populates="job", cascade="all, delete-orphan")
    audit_logs = relationship("AuditLog", back_populates="job", cascade="all, delete-orphan")


class Requirement(Base):
    """
    Stores individual business requirements extracted from raw content by Agent 1.
    """
    __tablename__ = "requirements"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    content = Column(Text, nullable=False)
    actors = Column(JSON, nullable=True)
    business_rules = Column(JSON, nullable=True)
    ambiguities = Column(JSON, nullable=True)
    conflicts = Column(JSON, nullable=True)
    confidence_score = Column(Float, nullable=False, default=1.0)
    trace_id = Column(String(100), nullable=False)
    created_at = Column(DateTime, default=get_utc_now)

    job = relationship("Job", back_populates="requirements")


class Story(Base):
    """
    Stores validated user stories with acceptance criteria generated by the pipeline.
    """
    __tablename__ = "stories"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    epic = Column(String(255), nullable=False)
    feature = Column(String(255), nullable=False)
    title = Column(String(255), nullable=False)
    user_story = Column(Text, nullable=False)  # As a... I want... So that...
    acceptance_criteria = Column(JSON, nullable=False)  # Given-When-Then criteria
    trace_mappings = Column(JSON, nullable=False)  # mapping back to raw requirement IDs
    validation_results = Column(JSON, nullable=True)  # validation metrics (INVEST checks, quality score)
    plain_text_summary = Column(Text, nullable=True)
    created_at = Column(DateTime, default=get_utc_now)

    job = relationship("Job", back_populates="stories")


class AuditLog(Base):
    """
    Captures node executions, retries, inputs, and outputs within LangGraph orchestration.
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    job_id = Column(String(36), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    node_name = Column(String(100), nullable=False)
    status = Column(String(50), nullable=False)  # STARTED, COMPLETED, FAILED, RETRY
    retries = Column(Integer, default=0)
    payload = Column(JSON, nullable=True)
    message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=get_utc_now)

    job = relationship("Job", back_populates="audit_logs")

# INTEGRATION NOTE
# Make sure to import this models.py module before triggering SQLAlchemy DB engine creation
# to register tables metadata correctly in Postgres.
