from enum import Enum
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime

# --- Enums ---

class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    INFO = "INFO"

class DecisionOutcome(str, Enum):
    PASS = "PASS"
    REWORK = "REWORK"
    MANUAL_REVIEW = "MANUAL_REVIEW"

# --- Context Models ---

class ValidationContext(BaseModel):
    requirements: List[Dict[str, Any]] = Field(..., description="Source requirements extracted by Agent 1")
    epics: List[Dict[str, Any]] = Field(..., description="Epic hierarchy planned by Agent 2")
    features: List[Dict[str, Any]] = Field(..., description="Feature hierarchy planned by Agent 2")
    stories: List[Dict[str, Any]] = Field(..., description="User stories generated by Agent 3")
    business_rules: List[Dict[str, Any]] = Field(..., description="Extracted business rules")
    acceptance_criteria: List[Dict[str, Any]] = Field(..., description="Acceptance criteria mapped per story")
    definition_of_done: Dict[str, Any] = Field(..., description="Enterprise Definition of Done criteria")
    dependencies: List[Dict[str, Any]] = Field(..., description="Declared inter-story and system dependencies")
    actors: List[Dict[str, Any]] = Field(..., description="System and business actors")
    systems: List[Dict[str, Any]] = Field(..., description="Downstream and integrated systems")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Job and execution metadata")

# --- Finding & Result Models ---

class ValidationFinding(BaseModel):
    id: str = Field(..., description="Unique finding ID")
    validator_name: str = Field(..., description="Validator that generated this finding")
    title: str = Field(..., description="Short title of the issue")
    description: str = Field(..., description="Detailed explanation of the issue")
    severity: Severity = Field(..., description="Severity classification")
    field: Optional[str] = Field(None, description="Affected field or section of the story")
    mitigation: Optional[str] = Field(None, description="Suggested action to resolve the issue")

class ValidatorResult(BaseModel):
    validator_name: str = Field(..., description="Name of the validator")
    status: str = Field(..., description="PASSED or FAILED")
    findings: List[ValidationFinding] = Field(default_factory=list, description="List of findings")
    execution_time: float = Field(..., description="Execution time in milliseconds")
    severity_summary: Dict[str, int] = Field(default_factory=dict, description="Findings count by severity")

class ValidationExecutionSummary(BaseModel):
    job_id: str = Field(..., description="Associated job ID")
    validators_passed: List[str] = Field(default_factory=list, description="Passed validators")
    validators_failed: List[str] = Field(default_factory=list, description="Failed validators")
    critical_count: int = Field(0, description="Total critical findings")
    major_count: int = Field(0, description="Total major findings")
    minor_count: int = Field(0, description="Total minor findings")
    info_count: int = Field(0, description="Total info findings")
    execution_time: float = Field(..., description="Total execution time in milliseconds")
    decision: DecisionOutcome = Field(..., description="Final decision outcome (PASS, REWORK, MANUAL_REVIEW)")

# --- Rework & Revision Models ---

class PreserveSection(BaseModel):
    title: str = Field(..., description="Story Title")
    actor: str = Field(..., description="Primary Actor")
    traceability_links: List[str] = Field(..., description="Verified Traceability Links")
    approved_sections: List[str] = Field(default_factory=list, description="Approved sections that must remain unchanged")
    approved_business_rules: List[str] = Field(default_factory=list, description="Approved business rules")

class ModifySection(BaseModel):
    acceptance_criteria: List[str] = Field(default_factory=list, description="Acceptance criteria requiring modifications")
    missing_business_rules: List[str] = Field(default_factory=list, description="Business rules requiring inclusion")
    wording: List[str] = Field(default_factory=list, description="Weak wording requiring refinement")
    coverage_gaps: List[str] = Field(default_factory=list, description="Identified coverage gaps")
    validator_failures: List[str] = Field(default_factory=list, description="Specific validator failures to address")

class RevisionPackage(BaseModel):
    package_id: str = Field(..., description="Unique revision package ID")
    job_id: str = Field(..., description="Associated job ID")
    retry_count: int = Field(..., description="Current retry attempt count")
    failed_validators: List[str] = Field(..., description="List of validators that failed")
    validation_report: Dict[str, Any] = Field(..., description="Summary report of the validation run")
    ba_comments: Optional[str] = Field(None, description="Comments from the Business Analyst")
    preserve_section: PreserveSection = Field(..., description="Sections to preserve")
    modify_section: ModifySection = Field(..., description="Sections to modify")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")

# --- Final Export Contract ---

class ValidatedStoryPackage(BaseModel):
    package_id: str = Field(..., description="Unique package ID")
    job_id: str = Field(..., description="Unique pipeline execution ID")
    stories: List[Dict[str, Any]] = Field(..., description="List of validated and approved user stories")
    traceability_links: Dict[str, Any] = Field(..., description="Graph-verified traceability mappings")
    coverage_metrics: Dict[str, Any] = Field(..., description="Requirement and business rule coverage scores")
    quality_metrics: Dict[str, Any] = Field(..., description="INVEST and semantic quality scores")
    approval_status: DecisionOutcome = Field(DecisionOutcome.PASS, description="Status confirming the package is ready for publishing")
    audit_metadata: Dict[str, Any] = Field(..., description="Sign-off details, timestamps, and reviewer info")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")

class ValidationEngineOutput(BaseModel):
    invest_results: List[Any] = Field(default_factory=list, description="INVEST scorecard metrics")
    hallucination_results: List[Any] = Field(default_factory=list, description="Audit of story details to requirements alignment")
    coverage_verified: List[str] = Field(default_factory=list, description="List of source requirement IDs trace mapped in stories")
    quality_score: float = Field(..., description="Aggregated metric score representing story set readiness (0-100)")
    is_approved: bool = Field(..., description="Flag identifying if validation meets approval thresholds (e.g. >= 80)")
    summary: Optional[ValidationExecutionSummary] = Field(None, description="Detailed validation execution summary")
