# Configurable settings for the Validation Engine

EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
DUPLICATE_THRESHOLD = 0.85
HALLUCINATION_THRESHOLD = 0.60
CONSISTENCY_THRESHOLD = 0.70

MIN_COVERAGE_PCT = 95.0
MIN_INVEST_PCT = 80.0
MAX_RETRIES = 3
